---
title: "Predi-Pitch: Snack on This Curve Whenever You Want"
author: "David Scolari, Harrison Snell, Brandon Williams"
date: "4/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(here)
path <- here()

source(file.path(path, 'code', 'dugout.R'))

load(file = file.path(path, 'output', 'tables', "overall_performance_all.RDs"))


foreach(id = 1:30) %do% {
  # make filenames according to loop index
  fname_type <- paste0("types", id, ".RDs")
  fname_zones <- paste0("zones", id, ".RDs")
  fname_bypitch <- paste0("by_pitch_performance", id, ".RDs")

  # load table outputs according to loop index
  load(file = file.path(path, 'output', 'tables', fname_type))
  load(file = file.path(path, 'output', 'tables', fname_zones))
  load(file = file.path(path, 'output', 'tables', fname_bypitch))
  }
```

```{r tables, include=TRUE}
overall_performance_all

types_Trevor_Rosenthal
types_Felix_Hernandez
types_Chris_Archer
types_Zach_Britton
types_Wade_Davis
types_Dallas_Keuchel
types_Corey_Kluber
types_Luke_Gregerson
types_David_Price
types_Max_Scherzer
types_Aroldis_Chapman
types_Clayton_Kershaw
types_Madison_Bumgarner
types_Sonny_Gray
types_Huston_Street
types_Brad_Boxberger
types_Zack_Greinke
types_Shawn_Tolleson
types_Jordan_Zimmermann
types_Jacob_deGrom
types_Gerrit_Cole
types_Mark_Melancon
types_Jake_Arrieta
types_Andrew_Miller
types_Stephen_Strasburg
types_Collin_McHugh
types_Michael_Wacha
types_Chris_Sale
types_Zack_Greinke
types_Yu_Darvish

by_pitch_performance_Trevor_Rosenthal
by_pitch_performance_Felix_Hernandez
by_pitch_performance_Chris_Archer
by_pitch_performance_Zach_Britton
by_pitch_performance_Wade_Davis
by_pitch_performance_Dallas_Keuchel
by_pitch_performance_Corey_Kluber
by_pitch_performance_Luke_Gregerson
by_pitch_performance_David_Price
by_pitch_performance_Max_Scherzer
by_pitch_performance_Aroldis_Chapman
by_pitch_performance_Clayton_Kershaw
by_pitch_performance_Madison_Bumgarner
by_pitch_performance_Sonny_Gray
by_pitch_performance_Huston_Street
by_pitch_performance_Brad_Boxberger
by_pitch_performance_Zack_Greinke
by_pitch_performance_Shawn_Tolleson
by_pitch_performance_Jordan_Zimmermann
by_pitch_performance_Jacob_deGrom
by_pitch_performance_Gerrit_Cole
by_pitch_performance_Mark_Melancon
by_pitch_performance_Jake_Arrieta
by_pitch_performance_Andrew_Miller
by_pitch_performance_Stephen_Strasburg
by_pitch_performance_Collin_McHugh
by_pitch_performance_Michael_Wacha
by_pitch_performance_Chris_Sale
by_pitch_performance_Zack_Greinke
by_pitch_performance_Yu_Darvish

```