library(caret)
library(tidyverse)
library(ggplot2)
library(glmnet)
library(gbm)
library(ggmap)
library(rpart)
library(rpart.plot)
library(randomForest)
library(rsample)
library(MASS)
library(modelr)
library(fastDummies)
library(scales)
library(here)
library(knitr)
library(readxl)
library(foreach)
library(groupdata2)
library(pdp)
library(arules)
library(arulesViz)
  
path <- here()
